In [1]:
import quickGCNs
import pickle
import MAGCN
import torch
from torch_geometric.data import Data

# 生成Graph数据

In [5]:
# 由于是无向图，因此有 4 条边：(0 -> 1), (1 -> 0), (1 -> 2), (2 -> 1)
edge_index = torch.tensor([[0, 1],
                           [1, 0],
                           [1, 2],
                           [2, 1]], dtype=torch.long)

# 节点的特征                           
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9]], dtype=torch.float)

# 节点的标签
y = torch.tensor([[1], [2], [3]], dtype=torch.float)

# 边的特征
edge_attr = torch.tensor([1, 2, 3, 4], dtype=torch.float)

# 组成图数据
data = Data(x=x, y=y, edge_index=edge_index.t().contiguous(), edge_attr=edge_attr)
data

# 多个图组成图时间序列
'''
for data in datas:
    data_list.append(data)

data_list是一个列表，装着图时间序列
'''

'\nfor data in datas:\n    data_list.append(data)\n\ndata_list是一个列表，装着图时间序列\n'

# 生成好的Graph数据集

In [2]:
dataset = pickle.load(open('graph_data/data_lb_1' +'.pkl', 'rb'))
dataset

[Data(edge_attr=[110], edge_index=[2, 110], x=[11, 8], y=[11, 1]),
 Data(edge_attr=[110], edge_index=[2, 110], x=[11, 8], y=[11, 1]),
 Data(edge_attr=[110], edge_index=[2, 110], x=[11, 8], y=[11, 1]),
 Data(edge_attr=[110], edge_index=[2, 110], x=[11, 8], y=[11, 1]),
 Data(edge_attr=[110], edge_index=[2, 110], x=[11, 8], y=[11, 1]),
 Data(edge_attr=[110], edge_index=[2, 110], x=[11, 8], y=[11, 1]),
 Data(edge_attr=[110], edge_index=[2, 110], x=[11, 8], y=[11, 1]),
 Data(edge_attr=[110], edge_index=[2, 110], x=[11, 8], y=[11, 1]),
 Data(edge_attr=[110], edge_index=[2, 110], x=[11, 8], y=[11, 1]),
 Data(edge_attr=[110], edge_index=[2, 110], x=[11, 8], y=[11, 1]),
 Data(edge_attr=[110], edge_index=[2, 110], x=[11, 8], y=[11, 1]),
 Data(edge_attr=[110], edge_index=[2, 110], x=[11, 8], y=[11, 1]),
 Data(edge_attr=[110], edge_index=[2, 110], x=[11, 8], y=[11, 1]),
 Data(edge_attr=[110], edge_index=[2, 110], x=[11, 8], y=[11, 1]),
 Data(edge_attr=[110], edge_index=[2, 110], x=[11, 8], y=[11, 

# 每一张图的$X$特征矩阵

In [13]:
dataset[0].x

tensor([[74.0000,  0.8000, 27.0000, 76.0000,  8.0000,  5.8750, 75.8330,  1.5830],
        [85.0000,  0.9000, 33.0000, 55.0000,  7.0000,  5.7500, 81.4170,  2.6670],
        [66.0000,  1.1000, 28.0000, 20.0000,  8.0000,  4.5420, 93.1670,  1.6670],
        [83.0000,  1.1000, 43.0000, 41.0000, 10.0000,  6.7080, 82.8330,  1.2080],
        [54.0000,  0.7000, 36.0000, 50.0000,  8.0000,  6.8330, 71.3330,  2.0830],
        [99.0000,  1.2000, 27.0000, 46.0000,  7.0000,  5.2500, 88.0420,  1.7080],
        [82.0000,  0.9000, 44.0000, 41.0000,  7.0000,  4.9580, 86.4580,  1.3330],
        [58.0000,  0.9000, 28.0000, 27.0000,  7.0000,  5.9580, 87.0830,  1.2500],
        [55.0000,  0.8000, 42.0000, 60.0000,  9.0000,  7.8750, 64.5830,  2.1250],
        [79.0000,  0.9000, 32.0000, 46.0000,  9.0000,  5.3750, 81.9580,  2.0830],
        [85.0000,  0.8000, 30.0000, 54.0000,  6.0000,  5.0830, 84.4170,  2.7500]])

# 每一张图的$y$向量

In [14]:
dataset[0].y

tensor([[48.],
        [60.],
        [50.],
        [34.],
        [32.],
        [66.],
        [61.],
        [30.],
        [23.],
        [58.],
        [58.]])

# 每一张图的edge矩阵（稀疏矩阵）

In [15]:
dataset[0].edge_index

tensor([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,
          1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,
          3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,
          5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,
          7,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
          9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 10, 10,
         10, 10],
        [ 6,  8,  5,  4,  3, 10,  7,  2,  9,  1,  6,  9, 10,  2,  5,  3,  8,  7,
          0,  4,  6,  9,  3, 10,  5,  1,  7,  4,  8,  0,  6,  7,  4,  8,  2,  5,
         10,  0,  9,  1,  6,  3,  8,  7,  5,  0, 10,  2,  9,  1,  6,  0,  4, 10,
          8,  3,  2,  7,  9,  1,  5, 10,  1,  2,  3,  9,  4,  8,  0,  7,  3,  6,
          4,  8,  5, 10,  2,  0,  9,  1,  6,  4,  0,  7,  3,  5, 10,  2,  9,  1,
          6, 10,  1,  2,  5,  3,  7,  8,  0,  4,  6,  9,  1,  5,  2,  7,  3,  8,
          

# 每一张图的edge特征，长度对应edge矩阵

In [16]:
dataset[0].edge_attr

tensor([0.8669, 0.6336, 0.6772, 0.1697, 0.0961, 0.0900, 0.0314, 0.0381, 0.0192,
        0.0214, 3.7486, 0.9536, 0.7642, 0.1256, 0.1058, 0.0328, 0.0203, 0.0175,
        0.0214, 0.0100, 2.7525, 0.4561, 0.2156, 0.2050, 0.1933, 0.1256, 0.0372,
        0.0292, 0.0311, 0.0381, 1.3961, 1.0658, 0.7953, 0.3147, 0.2156, 0.2267,
        0.0783, 0.0961, 0.0369, 0.0328, 0.8092, 0.7953, 0.6417, 0.6503, 0.3931,
        0.1697, 0.0642, 0.0292, 0.0156, 0.0100, 7.0803, 0.6772, 0.3931, 0.3744,
        0.2356, 0.2267, 0.1933, 0.1078, 0.0858, 0.1058, 7.0803, 5.1489, 3.7486,
        2.7525, 1.3961, 1.8158, 0.8092, 0.5558, 0.8669, 0.4058, 1.0658, 0.4058,
        0.6503, 0.2783, 0.1078, 0.0681, 0.0372, 0.0314, 0.0236, 0.0175, 0.5558,
        0.6417, 0.6336, 0.2783, 0.3147, 0.2356, 0.0750, 0.0311, 0.0222, 0.0203,
        1.8158, 0.7908, 0.9536, 0.4561, 0.0858, 0.0369, 0.0236, 0.0222, 0.0192,
        0.0156, 5.1489, 0.7908, 0.7642, 0.3744, 0.2050, 0.0681, 0.0783, 0.0750,
        0.0900, 0.0642], dtype=torch.flo

# 调用quickGCNs包

In [2]:
''' 
eval_score：选择评估指标（'mse'、'rmse'、'mae'、'r2'） str；
train_times：每组参数重复实验次数 int；
save_path：保存路径 str；
search_method：参数搜索方式（网格搜索'grid'，随机搜索'random'）str；
use_cuda：是否使用GPU加速（需要电脑支持）bool
'''
data_size = len(dataset)
split_rate = 0.7
train_dataset = dataset[:int(data_size * split_rate)]
test_dataset = dataset[int(data_size * split_rate):]
quickGCNs.fit(train_dataset, test_dataset, eval_score='r2', train_times=2, save_path='base_models', search_method='random', use_cuda=False)

# 运行训练多个GCN模型，保存最佳参数组合的评估结果并且画图保存，以及每次重复实验测试的结果。
# models保存了基础Pyg提供的GCN模型，可以自行添加。
# 每次运行会记录日志log，出现意外可以断点恢复。

# 使用qucikGCNs中的网格搜索grid_search函数训练自己写的GCN模型

In [4]:
''' 
Model：自制Pytorch GCN模型 或者 Pyg 提供的 GCN 模型 class；
eval_score：选择评估指标（'mse'、'rmse'、'mae'、'r2'） str；
train_times：每组参数重复实验次数 int；
save_path：保存路径 str；
search_method：参数搜索方式（网格搜索'grid'，随机搜索'random'）str；
use_cuda：是否使用GPU加速（需要电脑支持）bool；
id：输入int 1，作为断点日志log的开始
'''

quickGCNs.grid_search(train_dataset, test_dataset, Model=MAGCN.MAGCN, eval_score='r2', train_times=2, save_path='MAGCN', model_name='MAGCN', use_cuda=False, id=1)